- block:
    - name: Obtenir la liste des fichiers de sauvegarde
      find:
        paths: "global_backup_db/"
        patterns: "backup_*_EAZYTraining_*_global_db.sql"
      register: backup_files
  
    #- name: Supprimer les anciens fichiers
     # command: "rm {{ item.path }}"
      #loop: "{{ backup_files.files }}"
      #loop_control:
       # label: "{{ item.path }}"
      #when: item.path | regex_replace('^.{35}(.{2}).*', '\\1') != '23' 

    - name: Obtenir la date d'aujourd'hui
      set_fact:
        current_date: "{{ ansible_date_time.date }}"
    
    - name: Soustraire 2 jours de la date d'aujourd'hui
      set_fact:
        two_days_ago: "{{ ((current_date | to_datetime('%Y-%m-%d')) - (2 * 86400)) | strftime('%Y-%m-%d') }}"
    
    - name: Afficher la date d'aujourd'hui soustraite de 2 jours
      debug:
        var: two_days_ago
    
    - name: Comparer avec la sortie de l'expression régulière
      debug:
        msg: "oui"
      when: "item.path | regex_replace('^.{24}(.{10}).*', '\\1') == two_days_ago"
      loop: "{{ backup_files.files }}"
  tags:
    - cleanup_backup
