- block:
    - name: Obtenir la liste des fichiers de sauvegarde
      find:
        paths: "global_backup_db/"
        patterns: "backup_*_EAZYTraining_*_global_db.sql"
      register: backup_files
      
    - name: Afficher le résultat de regex_replace
      debug:
        #var: item.path | regex_search('backup_(\\d{4}-\\d{2}-\\d{2}-)(\\d{2})\\d{4}_EAZYTraining_\\w+_global_db.sql', '\\2') | default('') | slice(0, 2)
        var: item.path | regex_search('.{4}(.).')
      #db: "{{ item.path | regex_search('.{18}(.{2})') }}"
      loop: "{{ backup_files.files }}"
    - name: Supprimer les anciens fichiers
      command: "rm {{ item.path }}"
      loop: "{{ backup_files.files }}"
      when: "regex_search('backup_(\\d{4}-\\d{2}-\\d{2}-)(\\d{2})\\d{4}_EAZYTraining_\\w+_global_db.sql', '\\2') != '05' or '05' not in item.path"

  tags:
    - cleanup_backup
