- block:
    - name: Obtenir la liste des fichiers de sauvegarde
      find:
        paths: "global_backup_db/"
        patterns: "backup_*_EAZYTraining_*_global_db.sql"
      register: backup_files
      
    - name: Afficher le résultat de regex_replace
      debug:
        var: "item.path | regex_replace('^.{35}(.{2}).*', '\\1')"
      loop: "{{ backup_files.files }}"
    - name: Supprimer les anciens fichiers
      command: "rm {{ item.path }}"
      loop: "{{ backup_files.files }}"
      when: "item.path | regex_replace('^.{35}(.{2}).*', '\\1') != '19'"
  tags:
    - cleanup_backup
