- block:
    - name: Obtenir la liste des fichiers de sauvegarde
      find:
        paths: "global_backup_db/"
        patterns: "backup_*_EAZYTraining_*_global_db.sql"
      register: backup_files
      
    - name: Afficher le résultat de regex_replace
      debug:
        msg: "{{ 'Non' if item.path | regex_replace('^.{35}(.{2}).*', '\\1') != '05' else 'Oui' }}"
      loop: "{{ backup_files.files }}"
  
    - name: Supprimer les anciens fichiers
      command: "rm {{ item.path }}"
      loop: "{{ backup_files.files }}"
      when: "item.path | regex_replace('^.{35}(.{2}).*', '\\1') != '05' | string"
  tags:
    - cleanup_backup
