- block:
    - name: Obtenir la liste des fichiers de sauvegarde
      find:
        paths: "global_backup_db/"
        patterns: "backup_*_EAZYTraining_*_global_db.sql"
      register: backup_files
  
    - name: Supprimer les anciens fichiers
      command: "rm {{ item.path }}"
      loop: "{{ backup_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      when: item.path | regex_replace('^.{35}(.{2}).*', '\\1') != '23' 
  tags:
    - cleanup_backup
