- name: Ouvrir les dossiers plugins et malcare-security
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    recurse: yes
  loop:
    - { path: "{{ wordpress_directory }}/wp-content/plugins", mode: "0775" }
    - { path: "{{ wordpress_directory }}/wp-content/plugins/malcare-security", mode: "0777" }
  tags:
    - open_folders

- name: Fermer les dossiers plugins et malcare-security
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    recurse: yes
  loop:
    - { path: "{{ wordpress_directory }}/wp-content/plugins", mode: "0555" }
    - { path: "{{ wordpress_directory }}/wp-content/plugins/malcare-security", mode: "0777" }
  tags:
    - close_folders

