- block:
    - name: Copy Docker Compose files and init script
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: 0644
      with_items:
        - { src: 'docker-compose.j2', dest: '{{ compose_project_dir }}/docker-compose.yml' }
        - { src: 'init.sh.j2', dest: '{{ compose_project_dir }}/init.sh' }

    - name: Start WordPress container
      command:
        cmd: "docker compose -f docker-compose.yml up -d"
      args:
        chdir: "{{ compose_project_dir }}"

    - name: Exécuter le script dans le conteneur WordPress
      command: docker exec wordpress bash -c "chmod +x /usr/local/bin/init.sh && /usr/local/bin/init.sh apache2-foreground"
      failed_when: false

  tags:    # Modifiez ici pour placer le tag correctement
    - deploy

