- name: Backup site in google drive
  tags:
    - google_drive_backup
  block:
    - name: Ensure pip is present
      ansible.builtin.package:
        name: python3-pip
        state: present
      changed_when: false 

    - name: Install PyDrive
      ansible.builtin.pip:
        name: PyDrive
        state: present
      changed_when: false 

    - name: Upload the backup to Google Drive
      ansible.builtin.command: python3 backup.py
      changed_when: false      
