- name: Backup site in google drive
  tags:
    - google_drive_backup
  block:
    - name: Ensure pip is present
      ansible.builtin.package:
        name: python3-pip
        state: present
      changed_when: false 

    - name: Install PyDrive
      ansible.builtin.pip:
        name: PyDrive
        executable: /usr/local/bin/pip3.8
        state: present
      changed_when: false 

    - name: Create Pydrive folder
      ansible.builtin.command: mkdir -p "{{ compose_project_dir }}/Pydrive"
      changed_when: false 

    - name: Create backup script from template
      ansible.builtin.template:
        src: backup.py.j2
        dest: "{{ compose_project_dir }}/Pydrive/backup.py"
        mode: '0755'
      changed_when: false 

    - name: Copy settings.yaml to wordpress server
      ansible.builtin.copy:
        src: settings.yaml
        dest: "{{ compose_project_dir }}/Pydrive/"
      changed_when: false  

#    - name: Decrypt client_secrets.json
#      delegate_to: localhost
#      ansible.builtin.command: ansible-vault decrypt "client_secrets.json" --output "/home/vagrant/Pydrive/client_secrets.json" --vault-password '{{ google_drive_secret_key }}'
#      changed_when: false

#    - name: Copy credentials.txt to wordpress server
#      delegate_to: localhost
#      environment:
#        ANSIBLE_VAULT_PASSWORD: "{{ google_drive_credentials_key }}"
#      ansible.builtin.copy:
#        src: credentials.txt
#        dest: "{{ compose_project_dir }}/Pydrive/credentials.txt"
#        decrypt: yes

#    - name: Copy client_secrets.json to wordpress server
#      environment:
#        ANSIBLE_VAULT_PASSWORD: "{{ google_drive_secret_key }}"
#      ansible.builtin.copy:
#        src: client_secrets.json
#        dest: "{{ compose_project_dir }}/Pydrive/client_secrets.json"
#        decrypt: yes

    - name: Upload the backup to Google Drive
      ansible.builtin.command: /usr/local/bin/python3.8 {{ compose_project_dir }}/Pydrive/backup.py
      changed_when: false      
