---
- name: Restore site
  tags:
    - global_restore
  block:

    - name: Stop frontend container
      ansible.builtin.command:: docker stop {{ wordpress_container_name }}
      notify:
        - Global_restore_db

    - name: "Flush handlers backup and activate rights of plugins"
      ansible.builtin.meta: flush_handlers

    - name: Extraire le fichier ZIP
      ansible.builtin.command:: sudo unzip -o {{ restore_file_name.restore_files_path }}/{{ restore_file_name.restore_pattern }} -d unzip_folder/

    - name: Copier les fichiers extraits depuis unzip_folder au reperoire eazytraining
      ansible.builtin.command:: sh -c "sudo cp -r unzip_folder/* {{ wordpress_site }}"

    - name: Remove files from unzip folder
      ansible.builtin.command:: sh -c "sudo rm -r unzip_folder/*"

    - name: Changer le propriétaire et les permissions des répertoires
      #become: yes
      #become_user: "{{ system_user }}"
      ansible.builtin.file:
        path: "{{ wordpress_site }}"
        owner: centos
        group: 33
        recurse: yes

    - name: Changer les permissions du répertoire plugins
      ansible.builtin.file:
        path: "{{ wordpress_site }}/wp-content/plugins/"
        mode: "0775"
        recurse: yes


    - name: Changer les permissions du répertoire malcare-security
      ansible.builtin.file:
        path: "{{ wordpress_site }}/plugins/malcare-security"
        mode: "0777"
        recurse: yes

    - name: Start frontend container
      ansible.builtin.command:: docker start {{ wordpress_container_name }}
