---
- block:

    - name: Stop frontend container
      command: docker stop {{ wordpress_container_name }}
      notify:
        - global_restore_db

    - name: "Flush handlers backup and activate rights of plugins"
      meta: flush_handlers
    
    - name: Extraire le fichier ZIP 
      command: sudo unzip -o {{ restore_file_name.restore_files_path }}/{{ restore_file_name.restore_pattern }} -d unzip_folder/

    - name: Copier les fichiers extraits depuis unzip_folder au reperoire eazytraining
      command: sh -c "sudo cp -r unzip_folder/* {{ wordpress_site }}"

    - name: Remove files from unzip folder
      command: sh -c "sudo rm -r unzip_folder/*"
  tags:
    - global_restore

