---
- name: Installation des plugins
  command: /usr/local/bin/wp plugin install "{{ item }}" --allow-root --ssh=docker:{{ wordpress_container_name }}
  loop: "{{ plugins_to_install }}"
  when: plugins_to_install is defined and plugins_to_install | length > 0
  tags:
    - install_plugins

- name: Activation des plugins
  command: /usr/local/bin/wp plugin activate "{{ item }}" --allow-root --ssh=docker:{{ wordpress_container_name }}
  loop: "{{ plugins_to_activate }}"
  when: plugins_to_activate is defined and plugins_to_activate | length > 0
  tags:
    - activate_plugins

- block:
    - name: backuper avant Mise à jour de WordPress avec WP-CLI
      notify:
        - global_backup

    - name: "Flush handlers backup before update site"
      meta: flush_handlers
      
    - name: Mise à jour de WordPress avec WP-CLI
      command: /usr/local/bin/wp core update --allow-root --ssh=docker:{{ wordpress_container_name }}
      notify:
        - global_backup
  tags:
    - update_wordpress


