---
- name: Activation des thèmes
  ansible.builtin.command: /usr/local/bin/wp theme activate "{{ item }}" --allow-root --ssh=docker:{{ wordpress_container_name }}
  loop: "{{ themes_to_activate }}"
  when: themes_to_activate is defined and themes_to_activate | length > 0
  tags:
    - activate_themes
  changed_when: false

- name: Installation des thèmes
  ansible.builtin.command: /usr/local/bin/wp theme install "{{ item }}" --allow-root --ssh=docker:{{ wordpress_container_name }}
  loop: "{{ themes_to_install }}"
  when: themes_to_install is defined and themes_to_install | length > 0
  tags:
    - install_themes
  changed_when: false
