---
- name: Plugins restore
  tags:
    - plugins_restore
  block:
    - name: Extraire le fichier ZIP
      ansible.builtin.command: unzip -o "{{ restore_plugins_name.restore_files_path }}/{{ restore_plugins_name.restore_pattern }}" -d "unzip_folder/"
      changed_when: false

    - name: Copier les fichiers extraits depuis unzip_folder au reperoire eazytraining
      ansible.builtin.command: sudo rsync -a --delete unzip_folder/ {{ wordpress_site }}/wp-content/plugins/
      changed_when: false

    - name: Remove backup file from the WordPress
      ansible.builtin.command: sh -c "sudo rm -rf unzip_folder/*"
      changed_when: false
