- name: Include drive_backup and s3_backup_site task
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - drive_backup.yml
    - s3_backup_site.yml
    - s3_global_db_backup.yml
  tags:
    - s3_drive_backup
