---
- block:
    - name: Install botocore and boto3
      pip:
          name: botocore,boto3
          executable: /usr/local/bin/pip3.8
    - name: Synchroniser le répertoire local avec S3
      vars:
          ansible_python_interpreter: /usr/local/bin/python3.8
      aws_s3:
          bucket: "{{ s3_bucket_name }}"
          object: "{{ s3_remote_directory_db }}/{{ s3_filename_db }}"
          dest: "{{ compose_project_dir }}/s3_db_restore/{{ s3_filename_db }}"
          mode: get
          secret_key: "{{ aws_secret_key }}"
          access_key: "{{ aws_access_key}}"
          region: "{{ region }}"
          
    - name: Copier le fichier de sauvegarde vers le conteneur
      command: docker cp {{ s3_restore_db_name.restore_files_path }}/{{ s3_restore_db_name.restore_pattern }} db:{{ s3_restore_db_name.restore_pattern }}

    - name: Restaurer le fichier SQL dans la base de données MySQL
      command: docker exec db sh -c "exec mysql -u{{ wp_db_user }} -p{{ wp_db_psw }} {{ wp_db_name }} < {{ s3_restore_db_name.restore_pattern }}"

    - name: Remove file from wordpress container
      command: docker exec db rm {{ s3_restore_db_name.restore_pattern }}

  tags:
    - restore_db_s3

