---
- block:
    - name: Install botocore and boto3
      pip:
          name: botocore,boto3
          executable: /usr/local/bin/pip3.8
    - name: Synchroniser le répertoire local avec S3
      vars:
          ansible_python_interpreter: /usr/local/bin/python3.8
      command: "/usr/local/bin/aws s3 sync s3://{{s3_bucket_name}}/{{ s3_remote_directory_themes }} {{ compose_project_dir }}/s3_global_theme_restore/{{ s3_filename_themes }}  --no-guess-mime-type"
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key}}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}
  tags:
    - restore_themes_s3

