---
- name: Restore plugins from s3
  tags:
    - restore_plugins_s3
  block:

    - name: Install botocore and boto3 using pip3.8
      ansible.builtin.command: /usr/local/bin/pip3.8 install botocore boto3
      vars:
        ansible_python_interpreter: /usr/local/bin/python3.8
      changed_when: false

    - name: Vérifier l'installation d'AWS CLI
      ansible.builtin.command: "aws --version"
      register: aws_version
      changed_when: false
      ignore_errors: true  # Ignorer les erreurs si awscli n'est pas déjà installé

    - name: Télécharger et installer AWS CLI si ce n'est pas déjà installé
      ansible.builtin.command: "curl -o /tmp/awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip && unzip -q /tmp/awscliv2.zip && sudo /tmp/aws/install"
      when: "'not installed' in aws_version.stderr"
      changed_when: false

    - name: Synchronize S3 directory to local
      vars:
        ansible_python_interpreter: /usr/local/bin/python3.8
      ansible.builtin.command: "/usr/local/bin/aws s3 sync s3://{{ s3_bucket_name }}/{{ s3_remote_directory_plugins }} {{ compose_project_dir }}/s3_global_plugin_restore/{{ s3_filename_plugins }}  --no-guess-mime-type"
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      changed_when: false

    - name: Extraire le fichier ZIP
      ansible.builtin.command: unzip -o "{{ s3_restore_plugins_name.restore_files_path }}/{{ s3_filename_plugins }}/{{ s3_restore_plugins_name.restore_pattern }}" -d "unzip_folder/"
      changed_when: false

    - name: Copier les fichiers extraits depuis unzip_folder au reperoire eazytraining
      ansible.builtin.command: sudo rsync -a --delete unzip_folder/ {{ wordpress_site }}/wp-content/plugins/
      changed_when: false

    - name: Remove backup file from the WordPress
      ansible.builtin.command: sh -c "sudo rm -rf unzip_folder/*"
      changed_when: false
