---
- block:
    - name: Installer les paquets Python
      pip:
        name:
          - "botocore"
          - "boto3"
        executable: /usr/local/bin/pip3.8

    - name: Synchronize S3 directory to local
      vars:
          ansible_python_interpreter: /usr/local/bin/python3.8
      command: "/usr/local/bin/aws s3 sync s3://{{s3_bucket_name}}/{{ s3_remote_directory_plugins }} {{ compose_project_dir }}/s3_global_plugin_restore/{{ s3_filename_plugins }}  --no-guess-mime-type"
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key}}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
     # s3_sync:
      #  bucket: "backup-aurelie"
       # aws_access_key: "{{ aws_access_key}}"
       # aws_secret_key: "{{ aws_secret_key }}"
        #src: "{{ s3_remote_directory_plugins }}"
        #dest: "{{ compose_project_dir }}/s3_global_plugin_restore/{{ s3_filename_plugins }}"
        #region: "{{ region }}"

    - name: Extraire le fichier ZIP 
      command: unzip -o "{{ s3_restore_plugins_name.restore_files_path }}/{{ s3_restore_plugins_name.restore_pattern }}" -d "unzip_folder/"

    - name: Copier les fichiers extraits depuis unzip_folder au reperoire eazytraining
      command: sudo rsync -a --delete unzip_folder/ eazytraining/wp-content/plugins/

    - name: Remove backup file from the WordPress 
      command: sh -c "sudo rm -rf unzip_folder/*"         
  tags:
    - restore_plugins_s3

