---
- block:
    - name: Install botocore and boto3
      pip:
          name: botocore,boto3
          executable: /usr/local/bin/pip3.8
    - name: Synchroniser le répertoire local avec S3
      vars:
          ansible_python_interpreter: /usr/local/bin/python3.8
      aws_s3:
          bucket: "{{ s3_bucket_name }}"
          object: "{{ s3_remote_directory_site }}/{{ s3_filename_site }}"
          dest: "{{ compose_project_dir }}/s3_site_restore/{{ s3_filename_site }}"
          mode: get
          secret_key: "{{ aws_secret_key }}"
          access_key: "{{ aws_access_key}}"
          region: "{{ region }}"

    - name: Extraire le fichier ZIP 
      command: sudo unzip -o {{ s3_restore_file_name.restore_files_path }}/{{ s3_restore_file_name.restore_pattern }} -d unzip_folder/

    - name: Copier les fichiers extraits depuis unzip_folder au reperoire eazytraining
      command: sudo rsync -a --delete unzip_folder/eazytraining/ eazytraining/

    - name: Remove files from unzip folder
      command: sudo rm -r unzip_folder/eazytraining/       
  tags:
    - restore_site_s3

