---
- name: Restore specific theme from s3
  tags:
    - restore_specific_themes_s3
  block:
    - name: Synchroniser le répertoire local avec S3
      vars:
        ansible_python_interpreter: /usr/local/bin/python3.8
      aws_s3:
        bucket: "{{ s3_bucket_name }}"
        object: "{{ s3_remote_directory_specific_themes }}/{{ s3_filename_specific_themes }}"
        dest: "{{ compose_project_dir }}/s3_specific_theme_restore/{{ s3_filename_specific_themes }}"
        mode: get
        secret_key: "{{ aws_secret_key }}"
        access_key: "{{ aws_access_key }}"
        region: "{{ region }}"

    - name: Extraire le fichier ZIP du plugin
      ansible.builtin.command: sh -c "sudo unzip -o {{ s3_specific_theme_name_restore.restore_files_path }}/{{ s3_specific_theme_name_restore.restore_pattern }} -d unzip_folder"
      changed_when: false  # Indicate that the task should not be considered as having changed anything

    - name: Copier les fichiers extraits depuis unzip_folder au reperoire eazytraining
      ansible.builtin.command: sh -c "sudo rsync -a unzip_folder/ {{ wordpress_site }}/wp-content/themes/"
      changed_when: false  # Indicate that the task should not be considered as having changed anything

    - name: Remove backup file from the WordPress
      ansible.builtin.command: sh -c "sudo rm -rf unzip_folder/*"
      changed_when: false  # Indicate that the task should not be considered as having changed anything
