---
- block:
    - name: Install botocore and boto3
      pip:
          name: botocore,boto3
          executable: /usr/local/bin/pip3.8
    - name: Synchroniser le répertoire local avec S3
      vars:
          ansible_python_interpreter: /usr/local/bin/python3.8
      s3_sync:
          bucket: "{{ s3_bucket_name }}"
          file_root: "{{ specific_backup_themes }}"
          delete: false
          secret_key: "{{ aws_secret_key }}"
          access_key: "{{ aws_access_key}}"
          key_prefix: "{{ s3_remote_directory_specific_themes }}"
    
  tags:
    - s3_specific_themes_backup

