---
- block:
    - name: Synchroniser le répertoire local avec S3
      vars:
          ansible_python_interpreter: /usr/local/bin/python3.8
      s3_sync:
          bucket: "{{ s3_bucket_name }}"
          file_root: "{{ specific_backup_plugins }}"
          delete: false
          secret_key: "{{ aws_secret_key }}"
          access_key: "{{ aws_access_key}}"
          key_prefix: "{{ s3_remote_directory_specific_plugins }}"
    
  tags:
    - s3_specific_plugins_backup

