---
- block:
    - name: Trouver le fichier de sauvegarde du plugin sur l'hôte
      ansible.builtin.find:
        paths: "{{ specific_theme_name_restore.restore_files_path }}"
        patterns: "{{ specific_theme_name_restore.restore_pattern }}"  # Utiliser le motif de sauvegarde spécifique du plugin
      register: restore_theme_files

    - name: Extraire le fichier ZIP du plugin
      command: sh -c "sudo unzip -o {{ specific_theme_name_restore.restore_files_path }}/{{ specific_theme_name_restore.restore_pattern }} -d unzip_folder"

    - name: Copier les fichiers extraits depuis unzip_folder au reperoire eazytraining
      command: sh -c "sudo rsync -a unzip_folder/ {{ wordpress_site }}/wp-content/themes/"

    - name: Remove backup file from the WordPress
      command: sh -c "sudo rm -rf unzip_folder/*"

  tags:
    - theme_specific_restore
