---
- block:
    - name: Trouver le fichier de sauvegarde du plugin sur l'hôte
      ansible.builtin.find:
        paths: "{{ specific_plugin_name_restore.restore_files_path }}"
        patterns: "{{ specific_plugin_name_restore.restore_pattern }}"  # Utiliser le motif de sauvegarde spécifique du plugin
      register: restore_plugin_files

    - name: Extraire le fichier ZIP du plugin 
      command: sudo unzip -o {{ specific_plugin_name_restore.restore_files_path }}/{{ specific_plugin_name_restore.restore_pattern }} -d unzip_folder/

    - name: Copier les fichiers extraits depuis unzip_folder au reperoire eazytraining
      command: sudo rsync -a unzip_folder/ eazytraining/wp-content/plugins/

    - name: Remove backup file from the WordPress
      command: sh -c "sudo rm -rf unzip_folder/*"

  tags:
    - plugin_specific_restore

