---
- name: Désactivation des plugins
  command:  /usr/local/bin/wp plugin deactivate "{{ item }}" --allow-root --ssh=docker:{{ wordpress_container_name }}  --path='/var/www/html/
  loop: "{{ plugins_to_deactivate }}"
  when: plugins_to_deactivate is defined and plugins_to_deactivate | length > 0
  tags:
    - deactivate_plugins

- block:
    - name: Change ownership recursively
      become: yes
      become_user: root
      file:
        path: eazytraining
        state: directory
        recurse: yes
        owner: centos
        group: 33
        
    - name: Désinstallation des plugins
      command: docker exec --user 33 {{ wordpress_container_name }} wp plugin install "{{ item }}"
      loop: "{{ plugins_to_uninstall }}"
      when: plugins_to_uninstall is defined and plugins_to_uninstall | length > 0
  tags:
    - uninstall_plugins
