---
- block:
    - name: Désactivation du thème actuel
      command: /usr/local/bin/wp theme activate "{{ new_theme }}" --allow-root --ssh=docker:{{ wordpress_container_name }}
      vars:
        new_theme: "{{ new_theme_to_activate }}"
      when: new_theme_to_activate is defined
  tags:
    - deactivate_themes

- block:
    - name: Vérification du statut des thèmes à désinstaller
      command: "/usr/local/bin/wp theme status '{{ item }}' --allow-root --ssh=docker:{{ wordpress_container_name }}"
      loop: "{{ themes_to_uninstall }}"
      register: theme_status
      when: themes_to_uninstall is defined

    - name: Désinstallation des thèmes
      command: "/usr/local/bin/wp theme uninstall '{{ item }}' --allow-root --ssh=docker:{{ wordpress_container_name }}"
      loop: "{{ themes_to_uninstall }}"
      when: theme_status.results is defined and theme_status.results | selectattr('rc', 'eq', 0) | list | length == theme_status.results | list | length
      # La condition ci-dessus vérifie si tous les thèmes ont un statut de retour 0 (c'est-à-dire qu'ils existent) avant de désinstaller.
  tags:
    - uninstall_themes




