---
- block:
    - name: Désactivation du thème actuel
      command: /usr/local/bin/wp theme activate "{{ new_theme }}" --allow-root --ssh=docker:{{ wordpress_container_name }}
      vars:
        new_theme: "{{ new_theme_to_activate }}"
      when: new_theme_to_activate is defined
  tags:
    - deactivate_themes

- block:
    - name: Vérification du statut du thème à désinstaller
      command: /usr/local/bin/wp theme status "{{ theme_to_uninstall }}" --allow-root --ssh=docker:{{ wordpress_container_name }}
      register: theme_status
      when: theme_to_uninstall is defined

    - name: Désinstallation des thèmes
      command: /usr/local/bin/wp theme uninstall "{{ theme_to_uninstall }}" --allow-root --ssh=docker:{{ wordpress_container_name }}
      when: theme_status is defined and theme_status.stdout | regex_search('Status:\\s*inactive')
      # La condition ci-dessus vérifie si le statut du thème est "Inactive" avant de désinstaller.
  tags:
    - uninstall_themes




