---

- block:
    - name: Désinstallation des plugins
      command: /usr/local/bin/wp plugin uninstall "{{ item }}" --deactivate --allow-root --ssh=docker:{{ wordpress_container_name }}
      loop: "{{ plugins_to_uninstall }}"
      when: plugins_to_uninstall is defined and plugins_to_uninstall | length > 0
  tags:
    - uninstall_plugins
